name = "tally-room-reminder"
main = "worker.js"
compatibility_date = "2025-01-01"

[triggers]
crons = ["0 8 * * *"]          # ogni giorno alle 08:00 UTC

[vars]
REMIND_EVERY_DAYS = "3"
SITE_URL = "https://tallyrooms.com"

[[d1_databases]]
binding = "DB"
database_name = "tallyroom"
database_id = "fb4be4bf-3fdb-49aa-a2c9-804576112798"
