name = "tally-room"
pages_build_output_dir = "public"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "tallyroom"
database_id = "fb4be4bf-3fdb-49aa-a2c9-804576112798"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "tallyroom-photos"
